### ISSUE TITLE
Review break out properties in typings

### ISSUE THREAD

**Issue by rido-min** [digitaltwinconsortium/DTDLParser#80]
These properties are not available in the output of `ParseToJson` 

https://github.com/digitaltwinconsortium/DTDLParser/blob/f7d12847e2e2d69c61099423f6978ba8db6aa97b/javascript/generated/DtdlOm.d.ts#L145-L152

Need to figure out how to consume those types in the JS Sample

**Comment by jrdouceur** [comment]
I can't repro this failure.  I just ran a simple model through ParseToJson() on the latest preview package (1.0.35-preview-gf7d12847e2) and its output included:
```
{
  . . .
  "dtmi:test:anInterface;1": {
    . . .
    "contents": {
      "expectedDistance": "dtmi:test:aProperty;1",
      "currentDistance": "dtmi:test:aTelemetry;1",
      "setDistance": "dtmi:test:aCommand;1",
      "proximity": "dtmi:test:aRelationship;1"
    },
    "commands": {
      "setDistance": "dtmi:test:aCommand;1"
    },
    "components": {},
    "properties": {
      "expectedDistance": "dtmi:test:aProperty;1"
    },
    "relationships": {
      "proximity": "dtmi:test:aRelationship;1"
    },
    "telemetries": {
      "currentDistance": "dtmi:test:aTelemetry;1"
    },
    . . .
  },
  . . .
}
```

**Comment by rido-min** [comment]
should the new breakout properties reference the concrete interfaces?

from

```js
export interface InterfaceInfo extends EntityInfo {
  EntityKind: 'Interface';
  contents: { [name: string]: string };
  commands: { [name: string]: string };
  components: { [name: string]: string };
  properties: { [name: string]: string };
  relationships: { [name: string]: string };
  telemetries: { [name: string]: string };
  extends: string[];
  extendedBy: string[];
  schemas: string[];
}
```

to 

```js
export interface InterfaceInfo extends EntityInfo {
  EntityKind: 'Interface';
  contents: { [name: string]: ContentInfo };
  commands: { [name: string]: CommandInfo };
  components: { [name: string]: ComponentInfo };
  properties: { [name: string]: PropertyInfo };
  relationships: { [name: string]: RelationshipInfo };
  telemetries: { [name: string]: TelemetryInfo };
  extends: string[];
  extendedBy: string[];
  schemas: string[];
}

```

**Comment by jrdouceur** [comment]
The DtdlOm.d.ts file describes the JSON returned by ParseToJson(), which does not return a hierarchical structure.  The JSON object that is the value of, e.g., "components" maps name strings to DTMI strings, not to ComponentInfo JSON objects.  This is the same for the breakout properties as it is/was for the "contents" property.

**Comment by rido-min** [comment]
got it. 

I'm leaving this issue open until the JS sample is updated to reflect those properties (that will require to populate to full objects)
