### ISSUE TITLE
Fetch Units Information

### ISSUE THREAD

**Issue by Raysapps** [digitaltwinconsortium/DTDLParser#92]
Could you please advise on how to fetch Units" for all defined Unit Semantic types (Acceleration , Angle, AngularAcceleration....)?
I'm trying to access metadata defined in supplemental types, but I can't find any method or property to retrieve the "Unit" types.
For instance, defined unit types for 'AccelerationUnit' are
- centimetre per second squared
- gForce
- metre per second squared

`    {
        ModelParser modelParser = new();
        var supp = modelParser.GetSupplementalTypes();
        foreach (var sup in supp)
        {
           Console.WriteLine($"{sup.Key} --> {sup.Value.Type}");
           foreach (var prop in sup.Value.Properties)
            {
                Console.WriteLine($"{prop.Key} --> {prop.Value?.Type}");
            }
            Console.WriteLine();

        }
    }`

**Comment by rido-min** [comment]
there are different APIs for v2 or v3 models, this sample will give you some hints.

https://github.com/digitaltwinconsortium/DTDLParser/blob/687b88c7e4268921d16dc77268982dc60cdd4cbd/samples/DTDLParserResolveSample/DTInfoExtensions.cs#L118-L135

can you share the model and what would be your intended output?

**Comment by jrdouceur** [comment]
Added issue #93 proposing feature `ModelParser.GetImplicitElements()` method.

**Comment by rido-min** [comment]
reopening until we resolve #93

**Comment by jrdouceur** [comment]
@Raysapps, until we have a fuller solution, we have added rudimentary support for this request that is explained in [Tutorial12#inspect-available-unit-values](https://github.com/digitaltwinconsortium/DTDLParser/blob/main/tutorials/Tutorial12_InspectSupplementalTypesAndPropertiesV2.md#inspect-available-unit-values) and [Tutorial13#inspect-available-unit-values](https://github.com/digitaltwinconsortium/DTDLParser/blob/main/tutorials/Tutorial13_InspectSupplementalTypesAndPropertiesV3.md#inspect-available-unit-values).

**Comment by Raysapps** [comment]
Thank you for the new API's introduced to fetch units from the ModelParser. This feature is sufficient for getting all supported unit values. This issue has been resolved and closing now.
Best Regards,
Chandra Mohan
